//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActividadesComplementarias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadComplementaria
    {
        public ActividadComplementaria()
        {
            this.Grupos = new HashSet<Grupos>();
        }
    
        public int idActividadComplementaria { get; set; }
        public string nombreActComplementaria { get; set; }
        public string descripcion { get; set; }
        public int departamento { get; set; }
        public string modalidad { get; set; }
        public double noCreditos { get; set; }
    
        public virtual Departamento Departamento1 { get; set; }
        public virtual ICollection<Grupos> Grupos { get; set; }
    }
}
