//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActividadesComplementarias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadComplementaria
    {
        public ActividadComplementaria()
        {
            this.Grupos = new HashSet<Grupos>();
        }
    
        public int idActividadComplementaria { get; set; }
        public string nombreActComplementaria { get; set; }
        public string descripcion { get; set; }
        public int departamento { get; set; }
        public string modalidad { get; set; }
        public double noCreditos { get; set; }
    
        public virtual Departamento Departamento1 { get; set; }
        public virtual ICollection<Grupos> Grupos { get; set; }
    }
}
