//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActividadesComplementarias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadCursada
    {
        public int idAvtividadCursada { get; set; }
        public int idGrupo { get; set; }
        public int idEstudiante { get; set; }
        public string estatusActividad { get; set; }
        public string periodo { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Grupos Grupos { get; set; }
    }
}
