//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActividadesComplementarias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadCursada
    {
        public int idAvtividadCursada { get; set; }
        public int idGrupo { get; set; }
        public int idEstudiante { get; set; }
        public string estatusActividad { get; set; }
        public string periodo { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Grupos Grupos { get; set; }
    }
}
