//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActividadesComplementarias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera
    {
        public Carrera()
        {
            this.Estudiante = new HashSet<Estudiante>();
        }
    
        public int idCarrera { get; set; }
        public string nombreCarrera { get; set; }
        public int departamento { get; set; }
    
        public virtual Departamento Departamento1 { get; set; }
        public virtual ICollection<Estudiante> Estudiante { get; set; }
    }
}
