//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActividadesComplementarias.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CreditosComplementariosEntities : DbContext
    {
        public CreditosComplementariosEntities()
            : base("name=CreditosComplementariosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActividadCursada> ActividadCursada { get; set; }
        public DbSet<Carrera> Carrera { get; set; }
        public DbSet<Departamento> Departamento { get; set; }
        public DbSet<Estudiante> Estudiante { get; set; }
        public DbSet<Maestros> Maestros { get; set; }
        public DbSet<TipoMaestro> TipoMaestro { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<ActividadComplementaria> ActividadComplementaria { get; set; }
    }
}
