//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActividadesComplementarias.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CreditosComplementariosEntities : DbContext
    {
        public CreditosComplementariosEntities()
            : base("name=CreditosComplementariosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActividadComplementaria> ActividadComplementaria { get; set; }
        public DbSet<ActividadCursada> ActividadCursada { get; set; }
        public DbSet<Carrera> Carrera { get; set; }
        public DbSet<Departamento> Departamento { get; set; }
        public DbSet<Estudiante> Estudiante { get; set; }
        public DbSet<Grupos> Grupos { get; set; }
        public DbSet<Maestros> Maestros { get; set; }
        public DbSet<TipoMaestro> TipoMaestro { get; set; }
    
        [EdmFunction("CreditosComplementariosEntities", "listAsistencia")]
        public virtual IQueryable<listAsistencia_Result> listAsistencia(Nullable<int> id_actcomp, string periodo)
        {
            var id_actcompParameter = id_actcomp.HasValue ?
                new ObjectParameter("id_actcomp", id_actcomp) :
                new ObjectParameter("id_actcomp", typeof(int));
    
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<listAsistencia_Result>("[CreditosComplementariosEntities].[listAsistencia](@id_actcomp, @periodo)", id_actcompParameter, periodoParameter);
        }
    
        [EdmFunction("CreditosComplementariosEntities", "lst_byAcred")]
        public virtual IQueryable<lst_byAcred_Result> lst_byAcred(Nullable<int> id_estud, Nullable<int> id_actcomp, string periodo)
        {
            var id_estudParameter = id_estud.HasValue ?
                new ObjectParameter("id_estud", id_estud) :
                new ObjectParameter("id_estud", typeof(int));
    
            var id_actcompParameter = id_actcomp.HasValue ?
                new ObjectParameter("id_actcomp", id_actcomp) :
                new ObjectParameter("id_actcomp", typeof(int));
    
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<lst_byAcred_Result>("[CreditosComplementariosEntities].[lst_byAcred](@id_estud, @id_actcomp, @periodo)", id_estudParameter, id_actcompParameter, periodoParameter);
        }
    
        [EdmFunction("CreditosComplementariosEntities", "lst_byact")]
        public virtual IQueryable<lst_byact_Result> lst_byact(Nullable<int> id_actcomp, string periodo)
        {
            var id_actcompParameter = id_actcomp.HasValue ?
                new ObjectParameter("id_actcomp", id_actcomp) :
                new ObjectParameter("id_actcomp", typeof(int));
    
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<lst_byact_Result>("[CreditosComplementariosEntities].[lst_byact](@id_actcomp, @periodo)", id_actcompParameter, periodoParameter);
        }
    
        [EdmFunction("CreditosComplementariosEntities", "slctPeriodo")]
        public virtual IQueryable<slctPeriodo_Result> slctPeriodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<slctPeriodo_Result>("[CreditosComplementariosEntities].[slctPeriodo]()");
        }
    }
}
