//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActividadesComplementarias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public Departamento()
        {
            this.ActividadComplementaria = new HashSet<ActividadComplementaria>();
            this.Carrera = new HashSet<Carrera>();
            this.Maestros = new HashSet<Maestros>();
        }
    
        public int idDepartamento { get; set; }
        public string nombreDepartamento { get; set; }
    
        public virtual ICollection<ActividadComplementaria> ActividadComplementaria { get; set; }
        public virtual ICollection<Carrera> Carrera { get; set; }
        public virtual ICollection<Maestros> Maestros { get; set; }
    }
}
