//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActividadesComplementarias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public Departamento()
        {
            this.Maestros = new HashSet<Maestros>();
            this.Carrera = new HashSet<Carrera>();
            this.ActividadComplementaria = new HashSet<ActividadComplementaria>();
        }
    
        public int idDepartamento { get; set; }
        public string nombreDepartamento { get; set; }
    
        public virtual ICollection<Maestros> Maestros { get; set; }
        public virtual ICollection<Carrera> Carrera { get; set; }
        public virtual ICollection<ActividadComplementaria> ActividadComplementaria { get; set; }
    }
}
