//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActividadesComplementarias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public Estudiante()
        {
            this.ActividadCursada = new HashSet<ActividadCursada>();
        }
    
        public int idEstudiante { get; set; }
        public string nombreEstudiante { get; set; }
        public int carrera { get; set; }
        public Nullable<double> creditosComplementarios { get; set; }
        public string contraseñaEstudiante { get; set; }
        public string saltContraseña { get; set; }
    
        public virtual ICollection<ActividadCursada> ActividadCursada { get; set; }
        public virtual Carrera Carrera1 { get; set; }
    }
}
