//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActividadesComplementarias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        public Grupos()
        {
            this.ActividadCursada = new HashSet<ActividadCursada>();
        }
    
        public int idGrupo { get; set; }
        public string nombreGrupo { get; set; }
        public string maestro { get; set; }
        public int cupo { get; set; }
        public Nullable<int> inscritos { get; set; }
        public string horario { get; set; }
        public string lugar { get; set; }
        public int actividadComplementaria { get; set; }
    
        public virtual ActividadComplementaria ActividadComplementaria1 { get; set; }
        public virtual ICollection<ActividadCursada> ActividadCursada { get; set; }
        public virtual Maestros Maestros { get; set; }
    }
}
