//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActividadesComplementarias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestros
    {
        public Maestros()
        {
            this.ActividadCursada = new HashSet<ActividadCursada>();
        }
    
        public int idMaestro { get; set; }
        public string nombreMaestro { get; set; }
        public int departamentoMaestro { get; set; }
        public string tipoMaestro { get; set; }
        public string contraseñaMaestro { get; set; }
        public string saltContraseña { get; set; }
    
        public virtual ICollection<ActividadCursada> ActividadCursada { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual TipoMaestro TipoMaestro1 { get; set; }
    }
}
