//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActividadesComplementarias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestros
    {
        public Maestros()
        {
            this.Grupos = new HashSet<Grupos>();
        }
    
        public string idMaestro { get; set; }
        public string nombreMaestro { get; set; }
        public int departamentoMaestro { get; set; }
        public string tipoMaestro { get; set; }
        public string contraseñaMaestro { get; set; }
        public string saltContraseña { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual ICollection<Grupos> Grupos { get; set; }
        public virtual TipoMaestro TipoMaestro1 { get; set; }
    }
}
