//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActividadesComplementarias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMaestro
    {
        public TipoMaestro()
        {
            this.Maestros = new HashSet<Maestros>();
        }
    
        public string idTipoMaestro { get; set; }
        public string tipoMaestro1 { get; set; }
    
        public virtual ICollection<Maestros> Maestros { get; set; }
    }
}
