//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActividadesComplementarias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMaestro
    {
        public TipoMaestro()
        {
            this.Maestros = new HashSet<Maestros>();
        }
    
        public string idTipoMaestro { get; set; }
        public string tipoMaestro1 { get; set; }
    
        public virtual ICollection<Maestros> Maestros { get; set; }
    }
}
